# Generated by Django 2.0.12 on 2021-01-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0008_auto_20200105_1357'),
        ('df_order', '0003_auto_20210105_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(null=True, verbose_name='类型，1为满减')),
                ('name', models.CharField(default='', max_length=32, null=True, verbose_name='优惠券名称')),
                ('img', models.CharField(default='', max_length=64, null=True, verbose_name='图片的url地址')),
                ('start_time', models.DateTimeField(default='', null=True, verbose_name='优惠券起始时间')),
                ('money', models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='金额')),
                ('status', models.IntegerField(default='', verbose_name='0未开始，1进行中，-1是结束')),
                ('remarks', models.CharField(default='', max_length=512, null=True, verbose_name='优惠券的说明')),
                ('create_time', models.DateTimeField(default='', null=True, verbose_name='创建时间')),
                ('full_money', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='金额满')),
            ],
            options={
                'verbose_name': '优惠券信息',
                'verbose_name_plural': '优惠券信息',
            },
        ),
        migrations.CreateModel(
            name='Coupons_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_money', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='优惠券的金额')),
                ('order_final_amount', models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='订单的最终金额')),
                ('status', models.IntegerField(default='', verbose_name='日志状态: 默认为0，支付回调成功后为1')),
                ('create_time', models.DateTimeField(default='', null=True, verbose_name='领取时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户的id')),
            ],
            options={
                'verbose_name': '优惠券消费记录表',
                'verbose_name_plural': '优惠券消费记录表',
            },
        ),
        migrations.CreateModel(
            name='Coupons_recive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_money', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='优惠券的金额')),
                ('status', models.IntegerField(default='', verbose_name='状态，1为已使用，0为已领取未使用，-1为已过期')),
                ('create_time', models.DateTimeField(default='', null=True, verbose_name='领取时间')),
                ('full_money', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='金额满')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户的id')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_coupon.Coupons', verbose_name='优惠券的id')),
            ],
            options={
                'verbose_name': '优惠券领取记录表',
                'verbose_name_plural': '优惠券领取记录表',
            },
        ),
        migrations.AddField(
            model_name='coupons_logs',
            name='coupon_recive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_coupon.Coupons_recive', verbose_name='领取优惠券的id'),
        ),
        migrations.AddField(
            model_name='coupons_logs',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.OrderInfo', verbose_name='订单的id'),
        ),
    ]
