# Generated by Django 2.0.12 on 2021-01-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0008_auto_20200105_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ucoupontimes',
            field=models.IntegerField(default=10, max_length=1000, verbose_name='抽奖次数'),
        ),
    ]
