# Generated by Django 2.0.12 on 2021-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0009_userinfo_ucoupontimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='umoney',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='总消费额'),
        ),
    ]
