# Generated by Django 2.0.12 on 2021-01-05 23:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_goods', '0008_goodsinfo_endprice'),
        ('df_user', '0008_auto_20200105_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=512, verbose_name='评论内容')),
                ('point', models.IntegerField(default=5, verbose_name='评分')),
                ('create_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='评论时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
