# Generated by Django 2.0.12 on 2021-01-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinfo',
            name='create_time',
        ),
    ]
