# Generated by Django 2.0.12 on 2021-01-06 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_comments', '0002_remove_commentinfo_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='评论时间'),
        ),
    ]
